### PR TITLE
fix typo in 'dovecot is running' test

### PR DESCRIPTION
**Pull request by mburns**

### CODE REVIEW

**Comment by zuazo** [comment]
Hello @mburns,

Thanks for the fix. Please, could you fix this bug in the following files too?

* `test/integration/ldap/bats/default.bats`
* `test/integration/attributes/bats/default.bats`

Thanks again.

**Comment by mburns** [comment]
@zuazo - happy to!

**Comment by zuazo** [comment]
Wonderful :smiley:

**Comment by zuazo** [comment]
Released in [`2.2.0`](https://github.com/onddo/dovecot-cookbook/releases/tag/2.2.0).

**Pull request merged**
